[package]
name = "wlist_native_mock"
version = "0.1.0"
edition = "2021"

[dependencies]
# common
anyhow = "^1.0"
once_cell = "^1.19"
serde = { version = "^1.0", features = ["derive", "rc"] }
tokio = { version = "^1.40", features = ["sync", "rt-multi-thread", "macros"] }
thiserror = "^1.0"
dashmap = "^6.0"
## data
derive_more = { version = "^1.0", features = ["constructor", "display", "deref", "deref_mut"] }
chrono = { version = "~0.4", features = ["serde"] }
bitflags = "^2.6"
indexmap = { version = "^2.5", features = ["serde"] }
hashbrown = { version = "~0.14", features = ["serde"] }
rmp-serde = "^1.3"
## database
rusqlite = { version = "~0.32", features = ["chrono", "bundled"] }
libsimple = "~0.3"
rusqlite_regex = "~0.2"

# core
bytes = "^1.7"
## helper
rand = "~0.8"
faster-hex = "~0.9"
sha2 = "~0.10"
md-5 = "~0.10"
## client
